version: '3.8'

services:
  mcp_vcn:
    build:
      context: ./mcp_vcn
      dockerfile: Dockerfile
    container_name: mcp_vcn
    ports:
      - "8000:8000"
    networks:
      - vcn_network
    restart: unless-stopped
    # Nota: healthcheck removido para simplificar el arranque. El servicio
    # será iniciado primero, pero no se esperará a que esté 'listo' internamente.

  agente_vcn:
    build:
      context: ./agente_vcn
      dockerfile: Dockerfile
    container_name: agente_vcn
    ports:
      - "8001:8001"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - URL_MCP=${URL_MCP}
    networks:
      - vcn_network
    depends_on:
      - mcp_vcn
    restart: unless-stopped

  interfaz:
    build:
      context: ./interfaz
      dockerfile: Dockerfile
    container_name: interfaz_vcn
    ports:
      - "8501:8501"
    environment:
      - URL_CHAT=${URL_CHAT}
    networks:
      - vcn_network
    depends_on:
      - agente_vcn
    restart: unless-stopped

networks:
  vcn_network:
    driver: bridge
